name: Ame Digital GitHub Actions
on:
  push:
    branches:
    - main
    - master
    - develop
    - homolog
  pull_request:
    branches:
    - main
    - master
    - develop
    - homolog
jobs:
  EXEC_CYBERSECURITY_SCA:
    name: Cybersecurity / SCA
    uses: AmeDigital/ame-github-actions/.github/workflows/sca-actions.yml@master
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      USER_PACKAGE_DEPLOY: ${{ secrets.USER_PACKAGE_DEPLOY }}
      TOKEN_PACKAGE_DEPLOY: ${{ secrets.TOKEN_PACKAGE_DEPLOY }}
      CYBER_DB_USER: ${{ secrets.CYBER_DB_USER }}
      CYBER_DB_TOKEN: ${{ secrets.CYBER_DB_TOKEN }}
    with:
      SNYK_SCA_CHECK: true
      SNYK_THRESHOLD_SCA: high
      SNYK_ORG: tribe-cybersecurity
      GRADLE_APP: true
      NODE_BUILD_VERSION: 0
  EXEC_CYBERSECURITY_SAST:
    name: Cybersecurity / SAST
    uses: AmeDigital/ame-github-actions/.github/workflows/sast-actions.yml@master
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      CYBER_DB_USER: ${{ secrets.CYBER_DB_USER }}
      CYBER_DB_TOKEN: ${{ secrets.CYBER_DB_TOKEN }}
    with:
      SNYK_CODE_CHECK: true
      SNYK_ORG: tribe-cybersecurity
      SNYK_THRESHOLD_CODE: high
  EXEC_CYBERSECURITY_IAC:
    name: Cybersecurity / IaC
    uses: AmeDigital/ame-github-actions/.github/workflows/iac-actions.yml@master
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      CYBER_DB_USER: ${{ secrets.CYBER_DB_USER }}
      CYBER_DB_TOKEN: ${{ secrets.CYBER_DB_TOKEN }}
    with:
      SNYK_FAIL_ON: upgradable
      SNYK_ORG: tribe-cybersecurity
      CHECKOV_CHECK: true
  EXEC_CYBERSECURITY_SECRET_SCAN:
    name: Cybersecurity / Secret
    uses: AmeDigital/ame-github-actions/.github/workflows/secret-scan-actions.yml@master
    secrets:
      CYBER_DB_USER: ${{ secrets.CYBER_DB_USER }}
      CYBER_DB_TOKEN: ${{ secrets.CYBER_DB_TOKEN }}
    with:
      GITLEAKS_CHECK: true
      SEMGREP_CHECK: true
      TRUFFLEHOG_CHECK: false
      TRIVY_SECRET_CHECK: false
      SEMGREP_RULES: p/secrets p/ci
  EXEC_CYBERSECURITY_CONTAINER:
    name: Cybersecurity / Container
    uses: AmeDigital/ame-github-actions/.github/workflows/container-actions.yml@master
    with: {}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      PRISMACLOUD_USER: ${{ secrets.PRISMACLOUD_USER }}
      PRISMACLOUD_TOKEN: ${{ secrets.PRISMACLOUD_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EXEC_CYBERSECURITY_FIM:
    name: Cybersecurity / FIM
    uses: AmeDigital/ame-github-actions/.github/workflows/fim-actions.yml@master
    with:
      GRADLE_INTEGRITY_CHECK: true
  EXEC_CYBERSECURITY_MOBILE:
    name: Cybersecurity / Mobile
    uses: AmeDigital/ame-github-actions/.github/workflows/mobile-actions.yml@master
    with: {}
  EXEC_CORE_CODE_QUALITY:
    name: Core / Code Quality
    uses: AmeDigital/ame-github-actions/.github/workflows/code-quality-actions.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      USER_PACKAGE_DEPLOY: ${{ secrets.USER_PACKAGE_DEPLOY }}
      TOKEN_PACKAGE_DEPLOY: ${{ secrets.TOKEN_PACKAGE_DEPLOY }}
    with:
      JAVA_BUILD_VERSION: 11
  EXEC_DEVELOPER_ACTIONS:
    name: Developer / App
    uses: AmeDigital/ame-github-actions/.github/workflows/developer-actions.yml@master
    secrets:
      USER_PACKAGE_DEPLOY: ${{ secrets.USER_PACKAGE_DEPLOY }}
      TOKEN_PACKAGE_DEPLOY: ${{ secrets.TOKEN_PACKAGE_DEPLOY }}
    with:
      GRADLE_APP: true
      NODE_BUILD_VERSION: 0
      JAVA_BUILD_VERSION: 1
